### ISSUE TITLE
Allow for higher resolution displays

### ISSUE THREAD

**Issue by slambert** [binford2k/showoff#215]
It looks like the #preso .slide element is set to 1024x768. (If there isn't a way already) it would be nice to be able to scale to the size of the browser/display for projectors that can handle higher resolutions.

**Comment by slambert** [comment]
In the meantime, is there a way to override this? I tried some CSS but could not affect the overall size of the element.

**Comment by binford2k** [comment]
Sure. This should work for you.

``` css
    body > #preso,
    body > #preso > .slide {
        height: 100%;
        width: 100%;
    }
```
