### ISSUE TITLE
:first-child pseudo element causes weird placing when a <p> isn't first.

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#492]
Whoever thought this was a good idea?

``` css
  /* prepend the first element of the .handouts div with Notes: */
  .handouts > :first-child:before {
    display: block;
    font-weight: bold;
    content: "Notes:";
    border-top: 2px dashed #999;
    padding: 0.25em 0 0.5em 0;
  }
```

... oh yeah. Sorry about that. This was legacy from before we took ownership, so we were trying to style without changing upstream. We'll fix that soon.
