### ISSUE TITLE
Suggested styles for uber-centering slides

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#615]
snagged from #608 

```css
div.content.center {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
}
```
