### ISSUE TITLE
Add Gitlab CI documentation to deploy a Showoff application on Heroku

### ISSUE THREAD

**Issue by githarkiratITP** [binford2k/showoff#640]
I have successfully deployed a showoff presentation on [Heroku][2]. Because Heroku makes it so easy to integrate Github, I have also been able to add a [Github repository][3] that auto-deploys on Heroku. 

I want to setup the same thing in [Gitlab][1]. Is there a simple way of doing this? I am trying to use this [documentation](https://docs.gitlab.com/ce/ci/examples/test-and-deploy-ruby-application-to-heroku.html) but the deploys are failing. Please help?
 
  [1]:https://gitlab.com/harkirat.singh/lunar-teach
  [2]: https://lunar-teach.herokuapp.com/
  [3]: https://github.com/githarkiratITP/lunar-teach

**Comment by binford2k** [comment]
I'm sorry, I don't use Gitlab CI, so other than reading the docs, there's not much help I can offer. If you gist your deploy log, or whatever failure you're seeing, I could offer some advice though.

Did you remember to update your `Procfile` and `config.ru`?

**Comment by githarkiratITP** [comment]
@binford2k I did update the `Procfile` and `config.ru` for #632 and it started working... thanks for your help there... also I got Gitlab CI to work... this is what the `.gitlab-ci.yml` needs to look like

```
stages:
  - staging
  - production

before_script:
  - apt-get update -qy

staging:
  image: ruby:2.2
  stage: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=gitlab-ci-ruby-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY --strategy=git
  only:
    - staging

production:
  image: ruby:2.2
  stage: production
  script:
    - gem install dpl
    - dpl --provider=heroku --app=gitlab-ci-ruby-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY --strategy=git
  only:
    - master
```
