### ISSUE TITLE
styles are overly permissive

### ISSUE THREAD

**Issue by binford2k** [binford2k/showoff#766]
For example, take these styles:

``` css
.bar {
  height: 1.25em;
  background-color: #e74c3c;
  border: 1px solid #f45f5f;
  border-left: none;
  border-radius: 0 0.4em 0.4em 0;
}
```

Let's say someone makes a presentation about their sudsy new business venture and they label a photo with the class of `bar`. Totally reasonable to do. But then that photo ends up looking like:

<img width="1059" alt="screen shot 2017-05-02 at 7 13 16 am" src="https://cloud.githubusercontent.com/assets/1392917/25615742/ee0e57ba-2f06-11e7-98ad-4d8cbe02d7e7.png">

Those overly permissive styles are all over. We'll need to audit them and make them more appropriate. (even if that just means adding `showoff` to all the style declarations.
